### ISSUE TITLE
Review Todo list

### ISSUE THREAD

**Issue by zeroch** [zeroch/FailoverDetector#2]
- [x] Remove internal message
- [x] Add file copy completion message
- [x] Add timezone disclaimer
- [x] Reword raw data message
- [x] Show result message depends on which root cause
